/**
 * Downloads the two brand webfonts from Google Fonts and self-hosts them.
 *
 * Self-hosting matters here: the hero headline is the LCP element, and a
 * render-blocking round trip to a third-party font origin is the single most
 * common cause of a poor LCP score on marketing sites. Same-origin woff2 +
 * <link rel="preload"> keeps the headline paint on the critical path only once.
 *
 * Outfit -> display/headings (geometric, matches the logo wordmark)
 * Inter  -> body/UI
 * Sora   -> hero supporting copy (tighter geometric, distinct from Inter)
 *
 * Run with: npm run fonts   (only needed when the font choice changes)
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = path.join(root, 'public', 'fonts');

// A modern UA is required or the API serves legacy TTF instead of woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  { css: 'Outfit:wght@600;700;800', file: 'outfit' },
  { css: 'Inter:wght@400;500;600;700', file: 'inter' },
  { css: 'Sora:wght@400;500;600;700', file: 'sora' },
];

// Latin only — this site targets the US market.
const KEEP_SUBSETS = ['latin'];

async function fetchCss(family) {
  const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family).replace(/%3A/g, ':').replace(/%40/g, '@').replace(/%3B/g, ';')}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Google Fonts responded ${res.status} for ${family}`);
  return res.text();
}

/** Split the returned CSS into per-@font-face blocks tagged with their subset. */
function parseFaces(css) {
  const faces = [];
  const blockRe = /\/\*\s*([\w-\[\]]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g;
  let m;
  while ((m = blockRe.exec(css))) {
    const subset = m[1];
    const block = m[2];
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1] ?? '400';
    const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? 'normal';
    const src = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
    if (src) faces.push({ subset, weight, style, src, range });
  }
  return faces;
}

async function main() {
  await mkdir(FONT_DIR, { recursive: true });
  const rules = [];

  for (const family of FAMILIES) {
    const css = await fetchCss(family.css);
    const faces = parseFaces(css).filter((f) => KEEP_SUBSETS.includes(f.subset));
    if (!faces.length) throw new Error(`No ${KEEP_SUBSETS.join('/')} faces found for ${family.css}`);

    const name = family.css.split(':')[0];
    const weights = family.css.split('@')[1].split(';').map(Number);

    // Google returns one *variable* woff2 covering every requested weight, listed
    // once per weight. Downloading it once and declaring a weight range ships a
    // single file instead of four identical ones.
    const seen = new Map();
    for (const face of faces) {
      if (seen.has(face.src)) continue;
      const bin = await fetch(face.src, { headers: { 'User-Agent': UA } });
      if (!bin.ok) throw new Error(`Failed to download ${face.src}`);
      seen.set(face.src, Buffer.from(await bin.arrayBuffer()));
    }
    if (seen.size !== 1) throw new Error(`Expected one variable file for ${name}, got ${seen.size}`);

    const [buf] = seen.values();
    const filename = `${family.file}-var.woff2`;
    await writeFile(path.join(FONT_DIR, filename), buf);

    const range = `${Math.min(...weights)} ${Math.max(...weights)}`;
    rules.push(
      `@font-face {\n` +
        `  font-family: '${name}';\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${range};\n` +
        `  font-display: swap;\n` +
        `  src: url('/fonts/${filename}') format('woff2');\n` +
        (faces[0].range ? `  unicode-range: ${faces[0].range};\n` : '') +
        `}`
    );
    console.log(`${filename.padEnd(22)} ${(buf.length / 1024).toFixed(1)} KB  (weights ${range})`);
  }

  await writeFile(
    path.join(root, 'src', 'styles', 'fonts.css'),
    `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n${rules.join('\n\n')}\n`
  );
  console.log('\nwrote src/styles/fonts.css');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
